name: Gh-Pages

on:
  push:
    branches: [ main ]

permissions: 
    contents: write
    pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /gzr_revanced/